export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'get started',
    imgStart: false,
    img: require('../../images/svg1.svg'),
    alt: 'car',
    dark: true,
    primary: true,
    darkText: false
}
export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Unlimited Access",
  headline: "Login to your at any time",
  description:
    "We have you covered no matter where you are located. All you need is an internet connection and a phone or computer.",
  buttonLabel: "learn more",
  imgStart: true,
  img: require("../../images/svg2.svg"),
  alt: "money",
  dark: false,
  primary: false,
  darkText: true,
};
export const homeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Join our team",
  headline: "Creating an account is extremely easy",
  description:
    "Get everything set up and ready under 10 minutes. All you need to do is add your information and you're ready to go.",
  buttonLabel: "start now",
  imgStart: false,
  img: require("../../images/svg3.svg"),
  alt: "data",
  dark: false,
  primary: false,
  darkText: true,
};